### PR TITLE
Fix code and documentation per v=b1.

### LINKED ISSUE #15: Serve v=b1 signed exchanges
This is a tracking bug to make sure the AMP packager serves valid signed exchanges per the evolving v=b1 spec. Support for v=b0 would need to co-exist for a few months.

Spec changes being drafted here: https://github.com/WICG/webpackage/pull/232

At present, these Chromium changes seem relevant:

  - [ ] restrict :url scheme to https https://crrev.com/c/1114407
  - [ ] Apply scheme restriction to {cert,validity}-url https://crrev.com/c/1114403
  - [ ] Require CanSignHttpExchangesDraft cert extension https://crrev.com/c/1111485 (modulo https://github.com/WICG/webpackage/issues/238)
  - [ ] Add CT verification for Signed Exchange https://crrev.com/c/1056776
  - [ ] SignedExchange: Forbid RSA signatures https://crrev.com/c/1096578
  - [ ] Signed exchange: Check content-type of certificate chain https://crrev.com/c/1082175
  - [ ] Signed Exchange: Switch to b1 envelope format https://crrev.com/c/1081773
  - [ ] Update Signed Exchange's Signature header format to b1 https://crrev.com/c/1077111
  - [ ] Check the validity URL is same-origin with the request url https://crrev.com/c/1075833
  - [ ] Signed exchange: Drop b0 support https://crrev.com/c/1074670
  - [ ] Introduce SignedExchangePrologue, the prologue parser for the b1 format https://crrev.com/c/1075883
  - [ ] Don't handle signed exchange transferred over plain HTTP https://crrev.com/c/1074915
  - [ ] Add OCSP check for Signed Exchange https://crrev.com/c/1060933
  - [ ] SignedExchangeVerifier: Support ecdsa_secp256r1_sha256 signature algorithm. https://crrev.com/c/979377

(I may eventually split out bugs for larger subprojects, like OCSP stapling.)

See also http://b/92515679.

### LINKED ISSUE #35: Automatically fetch SCT
https://github.com/WICG/webpackage/pull/267/files added some instructions on submitting a cert to CT and getting an SCT in return, in cases where the CA has not already attached it. This would be nice for the packager to support automatically, though not strictly necessary. At the very least, the documentation should be updated to include a reference to this.

### PR DESCRIPTION
**Pull request by twifkak**
Update cert requirements, validity-url generation, SCT generation and
documentation, cert-chain+cbor content-type, OCSP cache dir check,
inner content-type (text/html) and outer content-type (b0 -> b1).

This has been tested with a real SXG certificate against Chrome M69.

Fixes #35. Fixes #15. Addresses #36.

### CODE REVIEW

File: packager.go [hunk 1]
```diff
@@ -441,14 +447,18 @@ func (this *Packager) ServeHTTP(resp http.ResponseWriter, req *http.Request, par
 		return
 	}
 	now := time.Now()
+	validityHRef, err := url.Parse("/" + ValidityMapURL)
```
Comment (honeybadgerdontcare) [inline packager.go]: nit: if we're parsing a url by prefixing with a `/` then is it really a url? maybe it should be `validityURL, err := url.Parse("/" + ValidityMapPath)` or something.

Comment (twifkak) [reply packager.go]: Met you halfway; renamed ValidityMapURL to Path, but left validityHRef alone, to indicate it's a relative URL.

**Comment by twifkak** [comment]
Thanks! I'll merge this now so as to unblock future work, but if people have other comments I'm happy to address them in a future PR.
