### PR TITLE
Fix certcache to allow self-signed certs.

### LINKED ISSUE #352: Development mode requires a cert with an OCSP URL
Using the [instructions](https://github.com/WICG/webpackage/tree/master/go/signedexchange) to generate a self-signed cert, this doesn't work with `amppkg -development`:

```
2019/10/09 07:33:59 Updating OCSP; none cached yet.
2019/10/09 07:33:59 Updating OCSP; none cached yet.
2019/10/09 07:33:59 Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate
2019/10/09 07:33:59 Error computing OCSP midpoint: Parsing OCSP: no response matching the supplied certificate
2019/10/09 07:33:59 Error extracting OCSP server: Cert missing OCSPServer.
2019/10/09 07:33:59 Error parsing OCSP response: no response matching the supplied certificate
2019/10/09 07:33:59 OCSP failed health check.
```

We should fix `amppkg -development` not to require an OCSP URL, and in the meantime, document how to generate a self-signed cert with a fake AIA extension.

### PR DESCRIPTION
**Pull request by twifkak**
If the cert doesn't have an AIA extension with an OCSP responder URL,
then the cache will just include a fake (invalid) OCSP response in its
cert-chain+cbor. This is sufficient for displaying the SXG in Chrome
with --ignore-certificate-errors-spki-list.

Fixes #352.

### CODE REVIEW

**Comment by twifkak** [comment]
Note to reviewer: Marking this as "draft" because I'd rather not add *another* merge conflict for you to deal with in #349, plus maybe you have a better suggestion than my sentinel value hack.

File: packager/certloader/certloader.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ func PopulateCertCache(config *util.Config, key crypto.PrivateKey, developmentMo
 			return nil, errors.Wrapf(err, "checking %s", config.CertFile)
 		}
 	}
-	certCache := certcache.New(certs, config.OCSPCache)
+	certCache := certcache.New(certs, config.OCSPCache, developmentMode)
```
Comment (banaag) [inline packager/certloader/certloader.go]: I think you need to modify the certcache instantiation in gateway_server as well.

File: packager/certcache/certcache.go [hunk 2]
```diff
@@ -51,6 +51,10 @@ const maxOCSPResponseBytes = 1024 * 1024
 // How often to check if OCSP stapling needs updating.
 const ocspCheckInterval = 1 * time.Hour
 
+// Sentinel value used to communicate that a returned OCSP was fake, and the caller should not attempt to parse it.
+// No, I'm not proud.
+var fakeOCSP = []byte("fake ocsp response")
```
Comment (shigeki) [inline packager/certcache/certcache.go]: It is possible to create a valid OCSP response by using the private key of a self-signed cert such as gateway.go does. But it needs two certs to have the same private key.
https://github.com/ampproject/amppackager/blob/c9993b8ac4d17d1f05d3a1289956dadf3f9c370a/cmd/gateway_server/server.go#L148-L161

Or we can add an additional config to specify the issuer private key file to create a valid OCSP response.

Comment (twifkak) [reply packager/certcache/certcache.go]: Thanks for the pointer; I didn't remember that gateway server did that. However, it seems that the gateway server doesn't fully exercise the certcache code, so it succeeds, whereas my attempt to adopt this fails, with "error validating fake response:  bad OCSP signature: x509: ECDSA verification failure". Can you take a look at https://play.golang.org/p/8owXw00LsRx and see if you can find the error in my code?

Comment (shigeki) [reply packager/certcache/certcache.go]: The error can be resolved with the fix of  https://play.golang.org/p/CvVyUD-_tji . The private key needs to be the issuer key which corresponds to the self-signed cert key in this case.

Comment (twifkak) [reply packager/certcache/certcache.go]: Ah, yes, that makes perfect sense. Thanks for the bug fix; I've updated this to generate a GOOD OCSP response as suggested.
